# Generated by Django 4.2.3 on 2023-07-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducrCategory',
            new_name='ProductCategory',
        ),
    ]
